services:
  flask-app:
    image: flask-serf-app
    build:
      context: .
    ports:
      - "5000"
    networks:
      serf-network:
        aliases:
          - flask-app
    command: >
      sh -c "serf agent -tag role=web -bind=0.0.0.0:7946 -join=flask-app & python app.py"

networks:
  serf-network:
    driver: bridge